name: Generate pacman animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
        # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        # Step 2: Generate the pacman contribution graph
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
            # GitHub username to generate the animation for
            github_user_name: Tweenwrld
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}